import assert from "node:assert/strict";
import test from "node:test";
import { EvidenceConflictError, EvidenceService, type EvidenceBundleRecord, type EvidenceMutation, type EvidenceServiceRepository } from "../lib/server/evidence-service.ts";
import type { StoredEvidenceFile } from "../lib/server/evidence-storage.ts";

const admin={userId:"admin",email:"a@x.test",displayName:"a",fullName:null};const settings={analyzerModel:"m",promptVersion:"p",schemaVersion:"s"};const input={title:"제목",purpose:"압박 분석"};
class Repo implements EvidenceServiceRepository {bundles:EvidenceBundleRecord[]=[];sources:StoredEvidenceFile[]=[];clips:never[]=[];audits:unknown[]=[];fail=false;async getBundle(id:string){return this.bundles.find(x=>x.id===id)??null}async listBundles(){return this.bundles}async listSources(id:string){return this.sources.filter(x=>x.bundleId===id)}async findSource(id:string){return this.sources.find(x=>x.id===id)??null}async listVideoClips(id:string){return this.clips.filter(x=>x.bundleId===id)}async findSourceByHash(id:string,h:string){return this.sources.find(x=>x.bundleId===id&&x.contentHash===h)??null}async describeDeleteImpact(sourceId:string){return{sourceId,cardIds:[],scenarioDraftIds:[]}}async createBundle(b:EvidenceBundleRecord,a:unknown){this.bundles.push(b);this.audits.push(a)}async applyMutation(m:EvidenceMutation){if(this.fail)return false;this.bundles=this.bundles.map(x=>x.id===m.current.id?m.next:x);if(m.sourceToInsert)this.sources.push(m.sourceToInsert);this.audits.push(m.audit);return true}}
test("purpose changes content hash and lost CAS is a 409",async()=>{const r=new Repo(),s=new EvidenceService({repository:r,settings});const b=await s.createBundle(input,admin);const n=await s.updateBundle(b.id,{purpose:"빌드업 분석"},admin);assert.notEqual(n.contentVersion,b.contentVersion);r.fail=true;await assert.rejects(()=>s.updateBundle(b.id,{purpose:"x"},admin),EvidenceConflictError)});
test("source registration versions and audits",async()=>{const r=new Repo(),s=new EvidenceService({repository:r,settings});const b=await s.createBundle(input,admin);await s.addSource({id:"x",bundleId:b.id,originalFileName:"x",mediaType:"text/plain",byteSize:1,contentHash:"h",storageKey:"o",extractedTextKey:null,extractionStatus:"completed",extractionError:null},admin);assert.equal(r.bundles[0]?.version,2);assert.equal((r.audits.at(-1) as {action:string}).action,"source.added")});
